name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          # Use the lowest version of Python supported
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: Run mypy
        run: uv run --group lint mypy django_cryptography/

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run pre-commit
        run: uv run --group lint pre-commit run --all-files
